### ISSUE TITLE
Failed to get repository: InvalidGitRepositoryError('/app',)

### ISSUE THREAD

**Issue by smartcreeper192** [vijos/vj4-docker#14]
Failed to get repository: InvalidGitRepositoryError('/app',)
log:
vj4-docker-web-1       | Failed to get repository: InvalidGitRepositoryError('/app',)
vj4-docker-web-1       | Traceback (most recent call last):
vj4-docker-web-1       |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
vj4-docker-web-1       |     "__main__", mod_spec)
vj4-docker-web-1       |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
vj4-docker-web-1       |     exec(code, run_globals)
vj4-docker-web-1       |   File "/app/vj4/server.py", line 67, in <module>
vj4-docker-web-1       |     sys.exit(main())
vj4-docker-web-1       |   File "/app/vj4/server.py", line 64, in main
vj4-docker-web-1       |     web.run_app(app.Application(), sock=sock, access_log=None, shutdown_timeout=0)
vj4-docker-web-1       |   File "/app/vj4/app.py", line 82, in __init__
vj4-docker-web-1       |     loop.run_until_complete(system.setup())
vj4-docker-web-1       |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
vj4-docker-web-1       |     return future.result()
vj4-docker-web-1       |   File "/app/vj4/model/system.py", line 123, in setup
vj4-docker-web-1       |     fdoc = await coll.find_one({'_id': 'user_counter'})
vj4-docker-web-1       |   File "/usr/local/lib/python3.6/site-packages/aiomongo/collection.py", line 502, in find_one
vj4-docker-web-1       |     async for item in result_cursor:
vj4-docker-web-1       |   File "/usr/local/lib/python3.6/site-packages/aiomongo/cursor.py", line 199, in __anext__
vj4-docker-web-1       |     is_refereshed = await self._refresh()
vj4-docker-web-1       |   File "/usr/local/lib/python3.6/site-packages/aiomongo/cursor.py", line 260, in _refresh
vj4-docker-web-1       |     helpers._check_command_response(doc['data'][0])
vj4-docker-web-1       |   File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 210, in _check_command_response
vj4-docker-web-1       |     raise OperationFailure(msg % errmsg, code, response)
vj4-docker-web-1       | pymongo.errors.OperationFailure: Unsupported OP_QUERY command: find. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal

**Comment by Gingmzmzx** [comment]
把yml里面的mongodb镜像改成`mongodb:4.4.0`
