### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by undefined-moe** [vijos/vj4-docker#3]
![image](https://user-images.githubusercontent.com/29992205/52552070-e4d90a00-2e19-11e9-8df6-f5b92e0767ea.png)
Followed the instructions.
Testcase uploaded.
Why it's always waiting?

**Comment by moesoha** [comment]
@masnn Have you configured the judger?

**Comment by undefined-moe** [comment]
I've updated the linux core.Problem solved.
Now the problem is I cannot register as the smtp account is not defined.
Where and how I can configure it?
________________________________
发件人: Soha Jin <notifications@github.com>
发送时间: 2019年2月11日 16:43
收件人: vijos/vj4-docker
抄送: masnn; Mention
主题: Re: [vijos/vj4-docker] Help Wanted (#3)


@masnn<https://github.com/masnn> Have you configured the judger?

―

**Comment by moesoha** [comment]
@masnn You can pass the arguments through environment variables like VJ_SMTP_HOST

You can refer to https://github.com/vijos/vj4/blob/377d626536da952f409448979695b6f211b2f118/vj4/service/mailer.py#L10 for a full argument list about mailer.

**Comment by undefined-moe** [comment]
It's still giving me Error 500.
I'm using outlook mail.
[cid:91cef0e0-56a6-4a3f-a31b-65b8b3eae2a7]
Is this OK?
________________________________
发件人: Soha Jin <notifications@github.com>
发送时间: 2019年2月11日 17:43
收件人: vijos/vj4-docker
抄送: masnn; Mention
主题: Re: [vijos/vj4-docker] Help Wanted (#3)


@masnn<https://github.com/masnn> You can pass the arguments through environment variables like VJ_SMTP_HOST

You can refer to https://github.com/vijos/vj4/blob/377d626536da952f409448979695b6f211b2f118/vj4/service/mailer.py#L10 for a full argument list about mailer.

―

**Comment by undefined-moe** [comment]
![image](https://user-images.githubusercontent.com/29992205/52557699-21613180-2e2b-11e9-9eef-672c2d4b2d3d.png)
Emm... something wrong with image upload

**Comment by moesoha** [comment]
@masnn Please attach the detail error message from logs.

**Comment by undefined-moe** [comment]
500 Internal Server Error
Server got itself in trouble

**Comment by moesoha** [comment]
@masnn use --debug flag plz, or you can get log from docker-compose logs

**Comment by undefined-moe** [comment]
```
[E 190211 10:58:00 base:247] System error by /register 222.240.154.116 1: SMTPConnectError('Error connecting to smtp.office365.com on port 587',)
web_1       | [E 190211 10:58:00 web_protocol:319] Error handling request
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.6/site-packages/aiosmtplib/smtp.py", line 81, in connect
web_1       |     ssl=self.ssl)
web_1       |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 809, in create_connection
web_1       |     sock, protocol_factory, ssl, server_hostname)
web_1       |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 835, in _create_connection_transport
web_1       |     yield from waiter
web_1       |   File "/usr/local/lib/python3.6/asyncio/sslproto.py", line 505, in data_received
web_1       |     ssldata, appdata = self._sslpipe.feed_ssldata(data)
web_1       |   File "/usr/local/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
web_1       |     self._sslobj.do_handshake()
web_1       |   File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
web_1       |     self._sslobj.do_handshake()
web_1       | ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:847)
web_1       |
web_1       | During handling of the above exception, another exception occurred:
web_1       |
web_1       | Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 390, in start
web_1       |     resp = await self._request_handler(request)
web_1       |   File "/usr/local/lib/python3.6/site-packages/aiohttp/web_app.py", line 366, in _handle
web_1       |     resp = await handler(request)
web_1       |   File "/app/src/vj4/handler/base.py", line 228, in __await__
web_1       |     yield from super(Handler, self).__await__()
web_1       |   File "/usr/local/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 740, in _iter
web_1       |     resp = await method()
web_1       |   File "/app/src/vj4/handler/base.py", line 453, in wrapped
web_1       |     return await coro(self, **kwargs, **await self.request.post())
web_1       |   File "/app/src/vj4/handler/base.py", line 496, in wrapped
web_1       |     return await coro(self, **kwargs)
web_1       |   File "/app/src/vj4/handler/user.py", line 57, in post
web_1       |     url=self.reverse_url('user_register_with_code', code=rid))
web_1       |   File "/app/src/vj4/handler/base.py", line 220, in send_mail
web_1       |     await mailer.send_mail(mail, '{0} - Vijos'.format(translate(title)), content)
web_1       |   File "/app/src/vj4/service/mailer.py", line 27, in send_mail
web_1       |     async with aiosmtplib.SMTP_SSL(hostname=options.smtp_host, port=options.smtp_port) as server:
web_1       |   File "/usr/local/lib/python3.6/site-packages/aiosmtplib/smtp.py", line 548, in __aenter__
web_1       |     await self.connect()
web_1       |   File "/usr/local/lib/python3.6/site-packages/aiosmtplib/smtp.py", line 85, in connect
web_1       |     raise SMTPConnectError(message)
web_1       | aiosmtplib.errors.SMTPConnectError: Error connecting to smtp.office365.com on port 587
```

**Comment by moesoha** [comment]
@masnn Oops, I took a look at codes in mailer.py. It seems that vj4 only supports SSL(port 465). Outlook only has STARTTLS(port 587) support.

Open an issue in vijos/vj4, or you can implement one yourself and pr it.

**Comment by undefined-moe** [comment]
And how can I change the footer......
![image](https://user-images.githubusercontent.com/29992205/52559694-f7127280-2e30-11e9-9936-74e503e3934c.png)

**Comment by undefined-moe** [comment]
Mail problem fixed.
I've used Tencent Exmail instead

**Comment by moesoha** [comment]
@masnn You can change it in vj4.model.builtin.FOOTER_EXTRA_HTMLS.

**Comment by undefined-moe** [comment]
![image](https://user-images.githubusercontent.com/29992205/52560151-558c2080-2e32-11e9-82e0-9ae6552d8647.png)

**Comment by moesoha** [comment]
@masnn I mean change the footer defined in vj4.model.builtin.FOOTER_EXTRA_HTMLS

**Comment by undefined-moe** [comment]
Which file?
I can't find where vj4.model.builtin.FOOTER_EXTRA_HTMLS is.

**Comment by moesoha** [comment]
@masnn PTAL https://github.com/vijos/vj4/blob/master/vj4/model/builtin.py#L309

**Comment by undefined-moe** [comment]
How can I change this file?
Fork the repo and modify Dockerfile?

**Comment by moesoha** [comment]
@masnn You can just write a simple Dockerfile like this.

FROM vijos/vj4:latest
ADD path/to/your/file.ext dest/in/container/file.ext


And build your own image.

**Comment by moesoha** [comment]
@masnn Of course you can use "volume" to map a modified file into the container.

**Comment by undefined-moe** [comment]
![image](https://user-images.githubusercontent.com/29992205/52562922-f5e64300-2e3a-11e9-88f2-7a919d52d8cf.png)
I wonder which folder I should use.

**Comment by moesoha** [comment]
@masnn check the Dockerfile in this repo (https://github.com/vijos/vj4-docker/blob/master/Dockerfile#L17), you will see it should be /app/src/vj4/model/builtin.py

**Comment by undefined-moe** [comment]
Thanks!
I've never used docker before.

**Comment by moesoha** [comment]
@masnn Then learn to use it.😁👍

**Comment by undefined-moe** [comment]
:(  I'm back.
```
Traceback (most recent call last):
web_1       |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
web_1       |     "__main__", mod_spec)
web_1       |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
web_1       |     exec(code, run_globals)
web_1       |   File "/app/src/vj4/server.py", line 67, in <module>
web_1       |     sys.exit(main())
web_1       |   File "/app/src/vj4/server.py", line 64, in main
web_1       |     web.run_app(app.Application(), sock=sock, access_log=None, shutdown_timeout=0)
web_1       |   File "/app/src/vj4/app.py", line 55, in __init__
web_1       |     loop.run_until_complete(asyncio.gather(tools.ensure_all_indexes(), bus.init()))
web_1       |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
web_1       |     return future.result()
web_1       |   File "/app/src/vj4/service/bus.py", line 16, in init
web_1       |     channel = await _consume()
web_1       |   File "/app/src/vj4/service/bus.py", line 21, in _consume
web_1       |     channel = await mq.channel('bus')
web_1       |   File "/app/src/vj4/mq.py", line 44, in channel
web_1       |     channel = await (await _connect()).channel()
web_1       |   File "/app/src/vj4/mq.py", line 20, in _connect
web_1       |     _, protocol = await aioamqp.connect(host=options.mq_host, virtualhost=options.mq_vhost)
web_1       |   File "/usr/local/lib/python3.6/site-packages/aioamqp/__init__.py", line 59, in connect
web_1       |     factory, host, port, **create_connection_kwargs
web_1       |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 739, in create_connection
web_1       |     infos = f1.result()
web_1       |   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
web_1       |     result = self.fn(*self.args, **self.kwargs)
web_1       |   File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
web_1       |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
web_1       | socket.gaierror: [Errno -2] Name or service not known
```

I had changed the server.
I copied the all the files and run docker-compose up -d
It's now throwing this error.
And the container 'web' is always restarting.

**Comment by undefined-moe** [comment]
I can start vj4-docker normally by removing the old data/ folder.

**Comment by moesoha** [comment]
@masnn Error is throw in mq.py. Obviously, rabbitmq cannot be found.

**Comment by undefined-moe** [comment]
![image](https://user-images.githubusercontent.com/29992205/52910327-fc5c3b00-32d0-11e9-8101-b34971211857.png)
The file is here

**Comment by moesoha** [comment]
@masnn rabbitmq may not starting

**Comment by undefined-moe** [comment]
![image](https://user-images.githubusercontent.com/29992205/52910350-47764e00-32d1-11e9-8072-caaff38497c1.png)
And this is the docker-compose.yml

**Comment by undefined-moe** [comment]
![image](https://user-images.githubusercontent.com/29992205/52910363-6f65b180-32d1-11e9-961f-34c658d9ff35.png)
This is the rabbitmq logs

**Comment by masnn** [comment]
```
rabbitmq_1  | []
rabbitmq_1  | "Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only"
rabbitmq_1  | {error_logger,error_msg}
rabbitmq_1  | #{label=>{proc_lib,crash},report=>[[{initial_call,{auth,init,['Argument__1']}},{pid,<0.59.0>},{registered_name,[]},{error_info,{error,"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only",[{auth,init_cookie,0,[{file,"auth.erl"},{line,286}]},{auth,init,1,[{file,"auth.erl"},{line,140}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}},{ancestors,[net_sup,kernel_sup,<0.46.0>]},{message_queue_len,0},{messages,[]},{links,[<0.57.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,610},{stack_size,27},{reductions,559}],[]]}
rabbitmq_1  | #{label=>{supervisor,start_error},report=>[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only",[{auth,init_cookie,0,[{file,"auth.erl"},{line,286}]},{auth,init,1,[{file,"auth.erl"},{line,140}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}},{offender,[{pid,undefined},{id,auth},{mfargs,{auth,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
rabbitmq_1  | #{label=>{supervisor,start_error},report=>[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{shutdown,{failed_to_start_child,auth,{"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only",[{auth,init_cookie,0,[{file,"auth.erl"},{line,286}]},{auth,init,1,[{file,"auth.erl"},{line,140}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}}}},{offender,[{pid,undefined},{id,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
rabbitmq_1  | #{label=>{proc_lib,crash},report=>[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.45.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only",[{auth,init_cookie,0,[{file,"auth.erl"},{line,286}]},{auth,init,1,[{file,"auth.erl"},{line,140}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}}}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,138}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}},{ancestors,[<0.44.0>]},{message_queue_len,1},{messages,[{'EXIT',<0.46.0>,normal}]},{links,[<0.44.0>,<0.43.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,987},{stack_size,27},{reductions,184}],[]]}
rabbitmq_1  | #{label=>{application_controller,exit},report=>[{application,kernel},{exited,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only",[{auth,init_cookie,0,[{file,"auth.erl"},{line,286}]},{auth,init,1,[{file,"auth.erl"},{line,140}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}}}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
rabbitmq_1  | {"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{\"Cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only\",[{auth,init_cookie,0,[{file,\"auth.erl\"},{line,286}]},{auth,init,1,[{file,\"auth.erl\"},{line,140}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}}}},{kernel,start,[normal,[]]}}}"}
rabbitmq_1  |     args:     format:     label: 2019-02-17 08:29:45.701849 crash_report        2019-02-17 08:29:45.704468 supervisor_report   2019-02-17 08:29:45.705941 supervisor_report   2019-02-17 08:29:45.707026 crash_report        2019-02-17 08:29:45.708091 std_info            Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,auth,{"Cookie file /var/lib/rabbitmq/.erlan
rabbitmq_1  |
rabbitmq_1  | Crash dump is being written to: /var/log/rabbitmq/erl_crash.dump...done
```

**Comment by moesoha** [comment]
@masnn Go and find out what happened with logs

**Comment by undefined-moe** [comment]
I had chmod it to 600.
Problem solved.Thanks!
